/**
 * 常用工具静态参考数据（MIME 对照表 / Linux 命令大全）
 */

export interface MimeEntry {
  ext: string;
  mime: string;
  type: string;
}

/** 常见文件扩展名 → MIME 对照表 */
export const MIME_TABLE: MimeEntry[] = [
  { ext: 'txt', mime: 'text/plain', type: '文本' },
  { ext: 'log', mime: 'text/plain', type: '文本' },
  { ext: 'ini', mime: 'text/plain', type: '文本' },
  { ext: 'conf', mime: 'text/plain', type: '文本' },
  { ext: 'md', mime: 'text/markdown', type: '文本' },
  { ext: 'html', mime: 'text/html', type: '文本' },
  { ext: 'htm', mime: 'text/html', type: '文本' },
  { ext: 'css', mime: 'text/css', type: '文本' },
  { ext: 'csv', mime: 'text/csv', type: '文本' },
  { ext: 'sql', mime: 'application/sql', type: '文本' },
  { ext: 'js', mime: 'text/javascript', type: '代码' },
  { ext: 'mjs', mime: 'text/javascript', type: '代码' },
  { ext: 'ts', mime: 'text/typescript', type: '代码' },
  { ext: 'tsx', mime: 'text/typescript', type: '代码' },
  { ext: 'jsx', mime: 'text/jsx', type: '代码' },
  { ext: 'vue', mime: 'text/x-vue', type: '代码' },
  { ext: 'py', mime: 'text/x-python', type: '代码' },
  { ext: 'java', mime: 'text/x-java-source', type: '代码' },
  { ext: 'c', mime: 'text/x-c', type: '代码' },
  { ext: 'h', mime: 'text/x-c', type: '代码' },
  { ext: 'cpp', mime: 'text/x-c++', type: '代码' },
  { ext: 'cs', mime: 'text/x-csharp', type: '代码' },
  { ext: 'go', mime: 'text/x-go', type: '代码' },
  { ext: 'rs', mime: 'text/x-rust', type: '代码' },
  { ext: 'php', mime: 'text/x-php', type: '代码' },
  { ext: 'rb', mime: 'text/x-ruby', type: '代码' },
  { ext: 'sh', mime: 'application/x-sh', type: '代码' },
  { ext: 'json', mime: 'application/json', type: '数据' },
  { ext: 'xml', mime: 'application/xml', type: '数据' },
  { ext: 'yaml', mime: 'application/yaml', type: '数据' },
  { ext: 'yml', mime: 'application/yaml', type: '数据' },
  { ext: 'toml', mime: 'application/toml', type: '数据' },
  { ext: 'pdf', mime: 'application/pdf', type: '文档' },
  { ext: 'doc', mime: 'application/msword', type: '文档' },
  {
    ext: 'docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    type: '文档',
  },
  { ext: 'xls', mime: 'application/vnd.ms-excel', type: '文档' },
  {
    ext: 'xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    type: '文档',
  },
  { ext: 'ppt', mime: 'application/vnd.ms-powerpoint', type: '文档' },
  {
    ext: 'pptx',
    mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    type: '文档',
  },
  { ext: 'png', mime: 'image/png', type: '图片' },
  { ext: 'jpg', mime: 'image/jpeg', type: '图片' },
  { ext: 'jpeg', mime: 'image/jpeg', type: '图片' },
  { ext: 'gif', mime: 'image/gif', type: '图片' },
  { ext: 'svg', mime: 'image/svg+xml', type: '图片' },
  { ext: 'webp', mime: 'image/webp', type: '图片' },
  { ext: 'bmp', mime: 'image/bmp', type: '图片' },
  { ext: 'ico', mime: 'image/x-icon', type: '图片' },
  { ext: 'tif', mime: 'image/tiff', type: '图片' },
  { ext: 'mp3', mime: 'audio/mpeg', type: '音频' },
  { ext: 'wav', mime: 'audio/wav', type: '音频' },
  { ext: 'ogg', mime: 'audio/ogg', type: '音频' },
  { ext: 'flac', mime: 'audio/flac', type: '音频' },
  { ext: 'aac', mime: 'audio/aac', type: '音频' },
  { ext: 'm4a', mime: 'audio/mp4', type: '音频' },
  { ext: 'mp4', mime: 'video/mp4', type: '视频' },
  { ext: 'webm', mime: 'video/webm', type: '视频' },
  { ext: 'avi', mime: 'video/x-msvideo', type: '视频' },
  { ext: 'mov', mime: 'video/quicktime', type: '视频' },
  { ext: 'mkv', mime: 'video/x-matroska', type: '视频' },
  { ext: 'wmv', mime: 'video/x-ms-wmv', type: '视频' },
  { ext: 'flv', mime: 'video/x-flv', type: '视频' },
  { ext: 'mpeg', mime: 'video/mpeg', type: '视频' },
  { ext: 'zip', mime: 'application/zip', type: '压缩' },
  { ext: 'gz', mime: 'application/gzip', type: '压缩' },
  { ext: 'tar', mime: 'application/x-tar', type: '压缩' },
  { ext: '7z', mime: 'application/x-7z-compressed', type: '压缩' },
  { ext: 'rar', mime: 'application/vnd.rar', type: '压缩' },
  { ext: 'bz2', mime: 'application/x-bzip2', type: '压缩' },
  { ext: 'xz', mime: 'application/x-xz', type: '压缩' },
  { ext: 'exe', mime: 'application/x-msdownload', type: '程序' },
  { ext: 'dll', mime: 'application/x-msdownload', type: '程序' },
  { ext: 'msi', mime: 'application/x-msdownload', type: '程序' },
  { ext: 'apk', mime: 'application/vnd.android.package-archive', type: '程序' },
  { ext: 'jar', mime: 'application/java-archive', type: '程序' },
  { ext: 'war', mime: 'application/java-archive', type: '程序' },
  { ext: 'iso', mime: 'application/x-iso9660-image', type: '程序' },
  { ext: 'wasm', mime: 'application/wasm', type: '程序' },
  { ext: 'ttf', mime: 'font/ttf', type: '字体' },
  { ext: 'otf', mime: 'font/otf', type: '字体' },
  { ext: 'woff', mime: 'font/woff', type: '字体' },
  { ext: 'woff2', mime: 'font/woff2', type: '字体' },
  { ext: 'eot', mime: 'application/vnd.ms-fontobject', type: '字体' },
];

export interface LinuxCommand {
  cmd: string;
  group: string;
  desc: string;
  example: string;
}

/** Linux 常用命令大全 */
export const LINUX_COMMANDS: LinuxCommand[] = [
  // ── 文件操作 ──
  {
    cmd: 'ls',
    group: '文件操作',
    desc: '列出目录内容',
    example: 'ls -lah /home',
  },
  { cmd: 'cd', group: '文件操作', desc: '切换目录', example: 'cd /var/log' },
  { cmd: 'pwd', group: '文件操作', desc: '显示当前工作目录', example: 'pwd' },
  {
    cmd: 'cp',
    group: '文件操作',
    desc: '复制文件/目录',
    example: 'cp -r src dist',
  },
  {
    cmd: 'mv',
    group: '文件操作',
    desc: '移动或重命名',
    example: 'mv old.txt new.txt',
  },
  {
    cmd: 'rm',
    group: '文件操作',
    desc: '删除文件/目录',
    example: 'rm -rf /tmp/cache',
  },
  {
    cmd: 'mkdir',
    group: '文件操作',
    desc: '创建目录',
    example: 'mkdir -p a/b/c',
  },
  {
    cmd: 'rmdir',
    group: '文件操作',
    desc: '删除空目录',
    example: 'rmdir empty',
  },
  {
    cmd: 'touch',
    group: '文件操作',
    desc: '创建空文件或更新时间戳',
    example: 'touch app.log',
  },
  {
    cmd: 'cat',
    group: '文件操作',
    desc: '查看文件内容',
    example: 'cat /etc/hosts',
  },
  {
    cmd: 'tac',
    group: '文件操作',
    desc: '倒序查看文件',
    example: 'tac app.log',
  },
  {
    cmd: 'head',
    group: '文件操作',
    desc: '查看文件开头',
    example: 'head -n 20 app.log',
  },
  {
    cmd: 'tail',
    group: '文件操作',
    desc: '查看文件末尾',
    example: 'tail -f app.log',
  },
  {
    cmd: 'less',
    group: '文件操作',
    desc: '分页查看（支持搜索）',
    example: 'less big.log',
  },
  {
    cmd: 'find',
    group: '文件操作',
    desc: '按条件查找文件',
    example: 'find / -name "*.conf" -mtime -7',
  },
  {
    cmd: 'locate',
    group: '文件操作',
    desc: '快速定位文件（需索引）',
    example: 'locate nginx.conf',
  },
  {
    cmd: 'which',
    group: '文件操作',
    desc: '查找命令所在路径',
    example: 'which python3',
  },
  {
    cmd: 'whereis',
    group: '文件操作',
    desc: '查找命令/手册位置',
    example: 'whereis ls',
  },
  {
    cmd: 'file',
    group: '文件操作',
    desc: '查看文件类型',
    example: 'file data.bin',
  },
  {
    cmd: 'stat',
    group: '文件操作',
    desc: '查看文件详细信息',
    example: 'stat /etc/hosts',
  },
  {
    cmd: 'ln',
    group: '文件操作',
    desc: '创建硬/软链接',
    example: 'ln -s /opt/app /usr/bin/app',
  },
  {
    cmd: 'chmod',
    group: '文件操作',
    desc: '修改文件权限',
    example: 'chmod 755 script.sh',
  },
  {
    cmd: 'chown',
    group: '文件操作',
    desc: '修改属主/属组',
    example: 'chown -R www:www /var/www',
  },
  // ── 文本处理 ──
  {
    cmd: 'grep',
    group: '文本处理',
    desc: '按正则匹配文本',
    example: 'grep -rn "ERROR" /var/log',
  },
  {
    cmd: 'sed',
    group: '文本处理',
    desc: '流式编辑替换',
    example: "sed -i 's/old/new/g' f.txt",
  },
  {
    cmd: 'awk',
    group: '文本处理',
    desc: '按列处理文本',
    example: "awk '{print $1}' data.txt",
  },
  {
    cmd: 'sort',
    group: '文本处理',
    desc: '排序',
    example: 'sort -t, -k2 -n data.csv',
  },
  {
    cmd: 'uniq',
    group: '文本处理',
    desc: '去重（需先排序）',
    example: 'sort list.txt | uniq -c',
  },
  {
    cmd: 'wc',
    group: '文本处理',
    desc: '统计行/词/字节',
    example: 'wc -l app.log',
  },
  {
    cmd: 'cut',
    group: '文本处理',
    desc: '截取指定列',
    example: 'cut -d: -f1 /etc/passwd',
  },
  {
    cmd: 'tr',
    group: '文本处理',
    desc: '字符替换/删除',
    example: "echo abc | tr 'a-z' 'A-Z'",
  },
  {
    cmd: 'diff',
    group: '文本处理',
    desc: '比较文件差异',
    example: 'diff -u old new',
  },
  {
    cmd: 'patch',
    group: '文本处理',
    desc: '应用补丁',
    example: 'patch -p1 < fix.patch',
  },
  {
    cmd: 'echo',
    group: '文本处理',
    desc: '输出文本',
    example: 'echo "hello" > f.txt',
  },
  {
    cmd: 'printf',
    group: '文本处理',
    desc: '格式化输出',
    example: "printf '%s=%d\\n' n 5",
  },
  {
    cmd: 'tee',
    group: '文本处理',
    desc: '输出并写入文件',
    example: 'cmd | tee out.log',
  },
  {
    cmd: 'xargs',
    group: '文本处理',
    desc: '将输入转为命令参数',
    example: 'find . -name "*.tmp" | xargs rm',
  },
  // ── 系统管理 ──
  {
    cmd: 'ps',
    group: '系统管理',
    desc: '查看进程',
    example: 'ps -ef | grep java',
  },
  { cmd: 'top', group: '系统管理', desc: '实时资源监控', example: 'top' },
  { cmd: 'htop', group: '系统管理', desc: '交互式进程监控', example: 'htop' },
  { cmd: 'kill', group: '系统管理', desc: '终止进程', example: 'kill -9 1234' },
  {
    cmd: 'pkill',
    group: '系统管理',
    desc: '按名称终止进程',
    example: 'pkill -f "node app.js"',
  },
  { cmd: 'free', group: '系统管理', desc: '查看内存', example: 'free -h' },
  {
    cmd: 'uptime',
    group: '系统管理',
    desc: '运行时长与负载',
    example: 'uptime',
  },
  { cmd: 'who', group: '系统管理', desc: '当前登录用户', example: 'who' },
  { cmd: 'whoami', group: '系统管理', desc: '当前用户名', example: 'whoami' },
  { cmd: 'id', group: '系统管理', desc: '用户/组信息', example: 'id' },
  { cmd: 'uname', group: '系统管理', desc: '内核信息', example: 'uname -a' },
  {
    cmd: 'hostname',
    group: '系统管理',
    desc: '主机名',
    example: 'hostname -I',
  },
  {
    cmd: 'date',
    group: '系统管理',
    desc: '日期时间',
    example: 'date +%F" "%T',
  },
  {
    cmd: 'crontab',
    group: '系统管理',
    desc: '定时任务',
    example: 'crontab -e',
  },
  {
    cmd: 'systemctl',
    group: '系统管理',
    desc: 'Systemd 服务管理',
    example: 'systemctl status nginx',
  },
  {
    cmd: 'journalctl',
    group: '系统管理',
    desc: '查看系统日志',
    example: 'journalctl -u nginx -f',
  },
  {
    cmd: 'dmesg',
    group: '系统管理',
    desc: '内核环形缓冲日志',
    example: 'dmesg | tail -20',
  },
  {
    cmd: 'shutdown',
    group: '系统管理',
    desc: '关机',
    example: 'shutdown -h now',
  },
  { cmd: 'reboot', group: '系统管理', desc: '重启', example: 'reboot' },
  {
    cmd: 'env',
    group: '系统管理',
    desc: '环境变量',
    example: 'env | grep PATH',
  },
  {
    cmd: 'export',
    group: '系统管理',
    desc: '导出环境变量',
    example: 'export JAVA_HOME=/opt/jdk',
  },
  // ── 网络 ──
  {
    cmd: 'ping',
    group: '网络',
    desc: '连通性测试',
    example: 'ping -c 4 baidu.com',
  },
  { cmd: 'ifconfig', group: '网络', desc: '网络接口配置', example: 'ifconfig' },
  { cmd: 'ip', group: '网络', desc: '网络对象管理', example: 'ip addr show' },
  {
    cmd: 'netstat',
    group: '网络',
    desc: '网络连接/端口',
    example: 'netstat -tlnp',
  },
  { cmd: 'ss', group: '网络', desc: '套接字统计', example: 'ss -tlnp' },
  {
    cmd: 'curl',
    group: '网络',
    desc: 'HTTP 客户端',
    example: 'curl -X POST -d @data.json url',
  },
  {
    cmd: 'wget',
    group: '网络',
    desc: '下载工具',
    example: 'wget -c https://x.com/a.zip',
  },
  {
    cmd: 'nslookup',
    group: '网络',
    desc: 'DNS 查询',
    example: 'nslookup example.com',
  },
  {
    cmd: 'dig',
    group: '网络',
    desc: 'DNS 详细查询',
    example: 'dig example.com A',
  },
  {
    cmd: 'traceroute',
    group: '网络',
    desc: '路由追踪',
    example: 'traceroute example.com',
  },
  { cmd: 'route', group: '网络', desc: '路由表', example: 'route -n' },
  {
    cmd: 'iptables',
    group: '网络',
    desc: '防火墙规则',
    example: 'iptables -L -n',
  },
  {
    cmd: 'nc',
    group: '网络',
    desc: '网络工具（端口探测）',
    example: 'nc -zv host 3306',
  },
  {
    cmd: 'ssh',
    group: '网络',
    desc: '远程登录',
    example: 'ssh -p 22 user@host',
  },
  {
    cmd: 'scp',
    group: '网络',
    desc: '远程拷贝',
    example: 'scp f.txt user@host:/tmp',
  },
  {
    cmd: 'rsync',
    group: '网络',
    desc: '增量同步',
    example: 'rsync -avz src/ dst/',
  },
  {
    cmd: 'nmap',
    group: '网络',
    desc: '端口扫描',
    example: 'nmap -sT 192.168.1.1',
  },
  // ── 权限安全 ──
  {
    cmd: 'sudo',
    group: '权限安全',
    desc: '提权执行',
    example: 'sudo apt update',
  },
  { cmd: 'su', group: '权限安全', desc: '切换用户', example: 'su - root' },
  { cmd: 'passwd', group: '权限安全', desc: '修改密码', example: 'passwd' },
  {
    cmd: 'useradd',
    group: '权限安全',
    desc: '新建用户',
    example: 'useradd -m alice',
  },
  {
    cmd: 'usermod',
    group: '权限安全',
    desc: '修改用户',
    example: 'usermod -aG docker alice',
  },
  {
    cmd: 'userdel',
    group: '权限安全',
    desc: '删除用户',
    example: 'userdel -r alice',
  },
  {
    cmd: 'groupadd',
    group: '权限安全',
    desc: '新建组',
    example: 'groupadd dev',
  },
  {
    cmd: 'umask',
    group: '权限安全',
    desc: '默认权限掩码',
    example: 'umask 022',
  },
  { cmd: 'last', group: '权限安全', desc: '登录记录', example: 'last -20' },
  {
    cmd: 'setfacl',
    group: '权限安全',
    desc: 'ACL 权限',
    example: 'setfacl -m u:alice:rw f.txt',
  },
  // ── 进程作业 ──
  { cmd: 'jobs', group: '进程作业', desc: '后台任务列表', example: 'jobs -l' },
  { cmd: 'bg', group: '进程作业', desc: '任务转入后台', example: 'bg %1' },
  { cmd: 'fg', group: '进程作业', desc: '任务调回前台', example: 'fg %1' },
  {
    cmd: 'nohup',
    group: '进程作业',
    desc: '忽略挂断运行',
    example: 'nohup java -jar app.jar &',
  },
  {
    cmd: 'wait',
    group: '进程作业',
    desc: '等待任务完成',
    example: 'wait $PID',
  },
  {
    cmd: 'disown',
    group: '进程作业',
    desc: '解除任务与终端绑定',
    example: 'disown -h %1',
  },
  // ── 包管理 ──
  {
    cmd: 'apt',
    group: '包管理',
    desc: 'Debian 系包管理',
    example: 'apt install -y nginx',
  },
  {
    cmd: 'yum',
    group: '包管理',
    desc: 'RHEL 系包管理',
    example: 'yum install nginx',
  },
  {
    cmd: 'dnf',
    group: '包管理',
    desc: '新一代 RHEL 包管理',
    example: 'dnf install nginx',
  },
  {
    cmd: 'rpm',
    group: '包管理',
    desc: 'RPM 包管理',
    example: 'rpm -ivh pkg.rpm',
  },
  {
    cmd: 'dpkg',
    group: '包管理',
    desc: 'Deb 包管理',
    example: 'dpkg -i pkg.deb',
  },
  {
    cmd: 'snap',
    group: '包管理',
    desc: 'Snap 应用管理',
    example: 'snap install code',
  },
  {
    cmd: 'npm',
    group: '包管理',
    desc: 'Node 包管理',
    example: 'npm i -g pnpm',
  },
  {
    cmd: 'pip',
    group: '包管理',
    desc: 'Python 包管理',
    example: 'pip install requests',
  },
  {
    cmd: 'mvn',
    group: '包管理',
    desc: 'Maven 构建',
    example: 'mvn clean package -DskipTests',
  },
  {
    cmd: 'gradle',
    group: '包管理',
    desc: 'Gradle 构建',
    example: 'gradle build',
  },
  {
    cmd: 'git',
    group: '包管理',
    desc: '版本控制',
    example: 'git commit -m "fix"',
  },
  {
    cmd: 'docker',
    group: '包管理',
    desc: '容器管理',
    example: 'docker compose up -d',
  },
  {
    cmd: 'kubectl',
    group: '包管理',
    desc: 'K8s 管理',
    example: 'kubectl get pods -A',
  },
  // ── 压缩归档 ──
  {
    cmd: 'tar',
    group: '压缩归档',
    desc: '归档压缩',
    example: 'tar -czf app.tar.gz dir/',
  },
  {
    cmd: 'zip',
    group: '压缩归档',
    desc: 'Zip 压缩',
    example: 'zip -r app.zip dir/',
  },
  {
    cmd: 'unzip',
    group: '压缩归档',
    desc: '解压 Zip',
    example: 'unzip app.zip -d out/',
  },
  {
    cmd: 'gzip',
    group: '压缩归档',
    desc: 'Gzip 压缩',
    example: 'gzip -9 app.log',
  },
  {
    cmd: 'gunzip',
    group: '压缩归档',
    desc: '解压 Gzip',
    example: 'gunzip app.log.gz',
  },
  {
    cmd: 'bzip2',
    group: '压缩归档',
    desc: 'Bzip2 压缩',
    example: 'bzip2 -k big.log',
  },
  { cmd: 'xz', group: '压缩归档', desc: 'Xz 压缩', example: 'xz -k big.log' },
  {
    cmd: '7z',
    group: '压缩归档',
    desc: '7-Zip 压缩',
    example: '7z a app.7z dir/',
  },
  // ── 磁盘存储 ──
  { cmd: 'df', group: '磁盘存储', desc: '磁盘空间', example: 'df -hT' },
  { cmd: 'du', group: '磁盘存储', desc: '目录占用', example: 'du -sh /var' },
  { cmd: 'fdisk', group: '磁盘存储', desc: '分区管理', example: 'fdisk -l' },
  { cmd: 'lsblk', group: '磁盘存储', desc: '块设备树', example: 'lsblk -f' },
  { cmd: 'blkid', group: '磁盘存储', desc: '分区 UUID/类型', example: 'blkid' },
  {
    cmd: 'mount',
    group: '磁盘存储',
    desc: '挂载',
    example: 'mount /dev/sdb1 /mnt',
  },
  { cmd: 'umount', group: '磁盘存储', desc: '卸载', example: 'umount /mnt' },
  {
    cmd: 'fsck',
    group: '磁盘存储',
    desc: '文件系统检查',
    example: 'fsck -f /dev/sdb1',
  },
  { cmd: 'sync', group: '磁盘存储', desc: '刷新缓存到磁盘', example: 'sync' },
];
