import type { VxeGridProps } from 'vxe-table';

export const columns: VxeGridProps['columns'] = [
  {
    field: 'name',
    title: '连接名称',
    headerAlign: 'center',
    align: 'left',
    minWidth: 140,
    showOverflow: true,
  },
  {
    field: 'dbType',
    title: '数据库类型',
    slots: { default: 'dbType' },
    width: 120,
    align: 'center',
    resizable: false,
  },
  {
    field: 'host',
    title: '主机',
    headerAlign: 'center',
    align: 'left',
    minWidth: 130,
    showOverflow: true,
  },
  {
    field: 'port',
    title: '端口',
    width: 80,
    align: 'center',
  },
  {
    field: 'database',
    title: '库名',
    headerAlign: 'center',
    align: 'left',
    minWidth: 130,
    showOverflow: true,
  },
  {
    field: 'schemaName',
    title: 'Schema',
    width: 100,
    align: 'center',
    showOverflow: true,
  },
  {
    field: 'username',
    title: '用户名',
    width: 110,
    align: 'center',
    showOverflow: true,
  },
  {
    field: 'remark',
    title: '备注',
    headerAlign: 'center',
    align: 'left',
    minWidth: 120,
    showOverflow: true,
  },
  {
    field: 'createTime',
    title: '创建时间',
    slots: { default: 'createTime' },
    width: 170,
    align: 'center',
    resizable: false,
  },
  {
    field: 'action',
    title: '操作',
    slots: { default: 'action' },
    fixed: 'right',
    align: 'center',
    width: 160,
    resizable: false,
  },
];
